### ISSUE TITLE
Native / built-in language ?

### ISSUE THREAD

**Issue by benrubson** [juanjonol/Unlock-Redux#11]
Hi,

And first thank you for this Unlock version with APFS support 👍 

Looks strange however, on a fresh Mac OS installation, to have to install [Python3](https://www.python.org/downloads/) just to be able to unlock the users' disk.

Mojave still has python2.7 built-in.
Did you think about using a built-in language, such as Python2.7 then, or Bash, or... ?
So that we would not have any external requirement.

Thank you 👍

**Comment by juanjonol** [comment]
Hi! Sorry for not taking the time to respond you until know.

Basically, I choose Python 3 for 2 main reasons:

- With this project I started learned Python, and I didn't want to learn an already old language.
- Python 2.7 is almost 10 years old and [it's well pass time for all Python projects to stop supporting it](https://python3statement.org). In fact, official support for Python 2 is ending in January 1, 2020.

Luckily, with macOS 10.15 Catalina (released this week), Apple **finally** includes Python 3! Sadly, [it looks like Apple may stop including Scripting Languages Runtimes altogether in future macOS versiones](https://developer.apple.com/documentation/macos_release_notes/macos_catalina_10_15_release_notes).

I hope this answer you question. Thank you for using Unlock-Redux!
