### ISSUE TITLE
Error installing (Newbie).

### ISSUE THREAD

**Issue by ghost** [juanjonol/Unlock-Redux#13]
Hi. I am new to GitHub and came across this site looking for a solution to having the user files on a separate volume to the OSX (Mojave) on APFS.
I have downloaded the zip file and also python (using HomeBrew).

As instructed I move to the folder containing the downloaded files and run "sudo install.py"
I get the following error:  "sudo: install.py: command not found"

I am new to this, so I am assuming a silly mistake. Please advise.

Tx
Stuart

**Comment by phaze9** [comment]
You need to run sudo ./install.py

**Comment by juanjonol** [comment]
@phaze9 thank you for helping @kiwidtrader!

I have to improve this script and its instructions. I hope I'll get time for it this summer. In the meantime, if you need more help don't hesitate to ask 😊
