### ISSUE TITLE
Args and return type of subprocess.run()

### ISSUE THREAD

**Issue by renauddetry** [juanjonol/Unlock-Redux#9]
I'm working with Python 3.5 on High Sierra. I had to modify the subprocess line of get_uuid() as follows:

`result = str(subprocess.run(command, stdout=subprocess.PIPE, check=True).stdout)`

I removed the _encoding_ argument which doesn't seem to exist in 3.5, and converted the returned value to a string. I don't know enough about Python 3 to figure out whether this will hold in pre or post 3.5.

Thanks a lot for providing an APFS-compatible Unlock, this repo spared me a lot of time!

**Comment by juanjonol** [comment]
Hi! I'm glad you find this program useful.

I'm going to test your modifications a little and then I'll push it to the repo. Thank you for your comment!
